### ISSUE TITLE
Toolbox Review: Content/Structure Mods

### ISSUE THREAD

**Issue by acatbennett** [LarsonLab/hyperpolarized-mri-toolbox#50]
Below I've listed some suggested modifications to directory structure as well as general toolbox content for your consideration. The applicable folders are linked for each section.
Related Review Issues:
#51 ,  #52

### RF Pulses
- Compensation and scaling functions to support kinetic modeling and/or simulations seem slightly homeless here. Is there an intuitive directory name that we could place them under and then detail in the README for this page?
[RF_pulses](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/RF_pulses)

### Spectral-Spatial
- Speaking more for myself, an example walking through the development of a spectral pulse with no slice selectivity would be helpful. May not be widely applicable for others however.
[RF_pulses/spectral_spatial](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/RF_pulses/spectral_spatial)

### Analysis
- Are the tests in this folder intended as true software tests, as in their purpose is to validate the functionality of individual fitting model scripts? It seems like they are not tests and more like demos, which in that case are they redundant with the demos provided in this directory? I think the naming could provide more clarity or use of a 'test' subdirectory at least.
[analysis](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/analysis)

### Exercises
- The *.m files in this directory seem to be solutions to the *.ipynb exercises, and should be moved under the /solutions/ subfolder. Or removed entirely considering solution notebooks are already provided in that directory.
[exercises](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/exercises)

### Denoising
- Is the pre-whitening function under coil combination more of a denoising step (and therefore belongs in this directory) or a precursor for coil-combination?
-  Can we either include or link to the denoising work that Yaewon has implemented (the name escapes me). If it is in a github repository then we could direct people to it quite easily and I think that would benefit our toolbox.
[reconstruction/denoising](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/reconstruction/denoising)

### Simulations
- I suggest we rename the scratch folder to "demos" or "examples" or "usage". The sensitivity example script within is a helpful guide and might be overlooked due to the naming of the folder.
- My same gripe from the analysis directory applies here. Let's not use "test" in a script name if it's not a test. But while we are here we can move any example scripts into a folder with the TR sensitivity.
[simulations](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/simulations)

Feel free to selectively follow these suggestions or comment if you would like clarification on any individual item.

**Comment by agentmess** [comment]
Great idea to be clear with using test vs demo, and also some clear storage with those

I moved the 'exercises' .m files to solutions

**Comment by agentmess** [comment]
Here is denoising repository
https://github.com/UCSF-HMTRC/hp13c_EPI-hosvd_denoising
@acatbennett - can you add where you think it works?

**Comment by agentmess** [comment]
Added link to denoising repository in reconstruction README
