### ISSUE TITLE
Toolbox Review: Modifications to Existing READMEs

### ISSUE THREAD

**Issue by acatbennett** [LarsonLab/hyperpolarized-mri-toolbox#51]
This is a list of comments and suggestions on existing toolbox READMEs.
Related review issues:
#50 , #52

### Main
- indicate which tools are not octave compatible
- list required matlab/octate package toolboxes
- convert the example citation for toolbox use into an embedded copyable block
[hyperpolarized-mri-toolbox](https://github.com/LarsonLab/hyperpolarized-mri-toolbox)

### Variable Flip Angles
- optimal_SNR_flips() should be optimal_SNR_angles()
- add brief callout for which demo scripts pertain to which vfa scripts
[RF_pulses/variable_flip_angles](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/RF_pulses/variable_flip_angles)

### Reconstruction
- Since we're not matching our headings to the folders exactly go ahead and add a space between Coil and Combination
- add hyperlink under EPI and EPSI to the demo notebooks
- add one-liner descriptions to coil combination and low rank methods
- make use of embeds, block quotes or even just formatting to make some of the larger reference blocks more readable
- add content to cover the phase processing tools
[reconstruction](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/reconstruction)

### EPSI Demo
- instead of enumerating the steps for usage I think a simple general description is all that is needed and then direct the user to the demo notebook for example usage.
[reconstruction/EPSI Demo](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/reconstruction/EPSI%20demo)

### Denoising
- convert the doi to a hyperlink
[reconstruction/denoising](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/reconstruction/denoising)

### Sample Data
- the doi links to the full text, I think that is sufficient and the hyperlinks to pubmed should be removed
[sample_data](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/sample_data)

### Simulations
- add mention of the ph and metabolic phantoms here but just point the user to their respective READMEs
[simulations](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/simulations)

**Comment by agentmess** [comment]
Suggestions for Main added

**Comment by agentmess** [comment]
variable flips updated

**Comment by agentmess** [comment]
reconstruction updated

**Comment by agentmess** [comment]
@acatbennett can you update the EPSI demo, denoising, sample data and simulation suggestions?  All these suggestions I think should be done.

**Comment by acatbennett** [comment]
slightly modified the suggestions for the simulations readme as the dedicated readmes for the metabolic phantom and pH phantom I refer to seem to not exist
