### ISSUE TITLE
Toolbox Review: Creation of New READMEs

### ISSUE THREAD

**Issue by acatbennett** [LarsonLab/hyperpolarized-mri-toolbox#52]
Related Review Issues:
#50 , #51 

### IDEAL
- add a brief (one-liner) description and any possible relevant references or published uses of the function
[reconstuction/IDEAL](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/reconstruction/IDEAL)

### Bicarbonate pH Simulation
- I think this needs a brief intro or at the very least a demo notebook (doesn't necessarily need to be a README)
[simulations/bicarbonate-pH_simulation](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/simulations/bicarbonate-pH_simulation)

### Trajectories
- listing example published uses of these trajectories could be nice
- also possibly a simple image or two to give immediate visualization of what the tool provides
[trajectories](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/trajectories)

### Utilities
- once visualization tools are added to the main branch a README will be included in this subfolder
- I am working on this (@acatbennett )
[utilities](https://github.com/LarsonLab/hyperpolarized-mri-toolbox/tree/master/utilities)

**Comment by agentmess** [comment]
IDEAL - this is not sufficient functionality yet so I've left it out

Simulation - done!
Trajectories - done

Utilities - @acatbennett to do, thanks!
